#ifndef ENUM_H__
#define ENUM_H__

enum AI_STATE
{
	AI_IDLE,
	AI_WALK,
	AI_CHASE,
	AI_SPECIAL_CHASE,
	AI_KNOLE_CHASE,
	AI_GETAWAY,
	AI_DISCOVERY,
	AI_ATTACK,
	AI_ATTACK2,
	AI_SPIN_ATTACK,
	AI_DOWN_ATTACK,
	AI_BOW_ATTACK,
	AI_BOW_ATTACK_READY,
	AI_HAND_ONE_TWO,
	AI_INIT_ATTACK,
	AI_BOSS_ATTACK,
	AI_BOSS_ATTACK2,
	AI_CRAZY_FOOT,
	AI_BOSS_COMBO_0,
	AI_BOSS_COMBO_1,
	AI_BOSS_COMBO_2,
	AI_ROUND_PUNCH_C,
	AI_DEFENCE_SWORD,
	AI_DAMAGED,
	AI_DAMAGED_LEFT,
	AI_DAMAGED_RIGHT,
	AI_DEFENCE,
	AI_DESH_BACK,
	AI_DAMAGE_SWO,
	AI_SPIN_A,
	AI_STAND_DOWN,
	AI_STAND_UP,
	AI_STUN,
	AI_REATTACK,
	AI_DAMAGED_DOWN,
	AI_DAM_UFA,
	AI_MOVE_DASH_L,
	AI_MOVE_DASH_R,
	AI_ROUND_PUNCH,
	AI_BOSS_STAND_DOWN,
	AI_DOWN,
	AI_DIE,
	AI_STATE_END,
};

enum PLAYER_SKILL_STATE
{
	PLAYER_GAIL,
	PLAYER_SHELTECHNIC,
	PLAYER_SPINCRUSH,
	PLAYER_JUMPATTACK,
	PLAYER_RISINGATTACK,
	PLAYER_SKILL_END,
};

enum ENEMY_TYPE 
{
	BABEGAZI_WARRIOR,
	BABEGAZI_AXE,
	BABEGAZI_BOW,
	KNOLE_COMMANDER,
	KNOLE_WARRIOR,
	HUMAN_BOSS,
	ENEMY_TYPE_END,

};


enum OBJECT_TYPE
{
	OBJECT_CRISTAL,
	OBJECT_CRISTAL2,
	OBEJCT_ICE_ROCK,
	OBJECT_LAMP_BONE_A,
	OBJECT_LAMP_BONE_B,
	OBJECT_LAMP_BONE_C,
	OBJECT_TYPE_END,
};


enum BULLET_STATE
{
	BULLET_BOOM,
	BULLET_SNIPER,
	BULLET_ARROW,
	BULLET_ICEMISSILE,
	BULLET_ICEMISSILE2,
	BULLET_END,
};

enum LIGHT_SPECIAL_INDEX
{
	LIGHT_NORMAL_STATE,
	LIGHT_A_STATE,
	LIGHT_B_STATE,
	LIGHT_C_STATE,
	LIGHT_BOSS_STATE,
	LIGHT_SPECIAL_INDEX_END,
};

enum OBSTACLE_TYPE
{
	OBSTACLE_GATE,
	OBSTACLE_ICETWISTER1,
	OBSTACLE_ICETWISTER2,
	OBSTACLE_SNOWBALL1,
	OBSTACLE_SNOWBALL2,
	OBSTACLE_TYPE_END,
};

enum UI_TYPE
{
	UI_NORMAL,
	UI_MAIN_BASE,
	UI_EXP_GAUAGE,
	UI_HP_GAUAGE,
	UI_MP_GAUAGE,
	UI_BOSS_GREEN_GAUAGE,
	UI_BOSS_YELLOW_GAUAGE,
	UI_BOSS_RED_GAUAGE,
	UI_BOSS_BAR,
	UI_LEVEL_UP,
	UI_LEVEL_UP_BACK,
	UI_NUMBERING_DAMAGE_1,
	UI_NUMBERING_DAMAGE_10,
	UI_NUMBERING_DAMAGE_100,
	UI_NUMBERING_DAMAGE_1000,
	UI_NUMBERING_DAMAGE_10000,
	UI_NUMBERING_DAMAGE_CRITICAL,
	UI_COMBO_1,
	UI_COMBO_10,
	UI_COMBO_100,
	UI_COMBO_CHAR,
	UI_COMBO_EFFECT,
	UI_HIT_EFFECT,
	UI_LOADING_BAR,
	UI_LOADING_GAGE,
	UI_LOADING_CHAR,
	UI_LOADING_EFFECT,
	UI_TYPE_END,
};

enum DECAL_TYPE
{
	DECAL_BOSS_ATTACK2,
	DECAL_CRAZY_FOOT,
	DECAL_BOSS_COMBO,
	DECAL_PALYER_GAIL,
	DECAL_PALYER_ATTSHEL,
	DECAL_PALYER_RISING_ATTACK,
	DECAL_PLAYER_SPIN_CRUSH_ATTACK,
	DECAL_PLAYER_UPPERKICK,
	DECAL_PLAYER_STUN_ATTACK,
	DECAL_PALYER_HOLDING_SHOT,
};

enum CAMERA_MDOE
{
	CAMERA_NORMAL,
	CAMERA_GATE,
	CAMERA_BOSS_ACTION,
	CAMERA_BOSS,
	CAMERA_SNOW_BALL,
};

enum EFFECT_TYPE
{
	EFFECT_HOLDING_BULLET,
	EFFECT_SNIPER_BULLET,
	EFFECT_EXPLOSION,
	EFFECT_SNIPER_EXPLOSION,
	EFFECT_PLAYER_MOVE,
	EFFECT_ARROW_EXPLOSION,
	EFFECT_BLOOD,
	EFFECT_BLUE_BLOOD,
	EFFECT_PURPLE_BLOOD,
};


enum CHANNEL 
{ 
	CHANNEL_BGM, 
	CHANNEL_PLAYER,
	CHANNEL_BABE_AXE,
	CHANNEL_BABE_WARRIOR,
	CHANNEL_BABE_BOW,
	CHANNEL_KNOLE_COMMANDER,
	CHANNEL_KNOLE_WARRIOR,
	CHANNEL_BOSS,
	CHANNEL_EFFECT,

	CHANNEL_END 
};


#endif
